# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txn',
            name='txn_amt',
        ),
        migrations.RemoveField(
            model_name='txn',
            name='txn_id',
        ),
    ]
