# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 01:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0002_auto_20170906_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='txn',
            name='txn_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
