# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0004_auto_20170906_0139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='txn',
            name='id',
        ),
        migrations.AlterField(
            model_name='txn',
            name='txn_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='txn',
            name='txn_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
