# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0006_auto_20170915_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2c_txn',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='b2c_txn',
            name='total_gst',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='b2c_txn',
            name='b2c_txn_amt',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='b2c_txn',
            name='b2c_txn_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
