# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-16 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0007_auto_20170916_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesses',
            name='prod_count',
        ),
        migrations.RemoveField(
            model_name='businesses',
            name='turnover',
        ),
        migrations.AlterField(
            model_name='b2c_txn',
            name='total_gst',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
