# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0009_remove_products_hsn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='b2c_txn',
            old_name='prod',
            new_name='prod_id',
        ),
        migrations.AddField(
            model_name='b2b_txn',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='b2b_txn',
            name='total_gst',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='b2c_txn',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='b2b_txn',
            name='b2b_txn_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='b2c_txn',
            name='total_gst',
            field=models.FloatField(null=True),
        ),
    ]
