# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gst', '0010_auto_20170920_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='b2c_txn',
            name='unit_price',
            field=models.IntegerField(null=True),
        ),
    ]
